#index:
#    path: /
#    controller: App\Controller\DefaultController::index

alumno_notas:
    path: /alumno/{id}/notas
    controller: App\Controller\AlumnoController::notas
    
alumno_asignaturas:
    path: /alumno/{id}/asignaturas
    controller: App\Controller\AlumnoController::asignaturas
    
alumno_add_asignatura:
    path: /alumno/{id}/asignaturas/new
    controller: App\Controller\AlumnoController::newAsignatura
    
alumno_remove_asignatura:
    path: /alumno/{id}/asignatura/{ida}remove
    controller: App\Controller\AlumnoController::removeAsignaturas
